# permissions for end users to view clustregcreds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustregcred-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: imagesecretsyncoperator
    app.kubernetes.io/part-of: imagesecretsyncoperator
    app.kubernetes.io/managed-by: kustomize
  name: clustregcred-viewer-role
rules:
- apiGroups:
  - imageregistrycredential.pradix.io
  resources:
  - clustregcreds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imageregistrycredential.pradix.io
  resources:
  - clustregcreds/status
  verbs:
  - get
